### ISSUE TITLE
Incomplete CLI spec

### ISSUE THREAD

**Issue by Frijol** [tessel/v2-cli#11]
I don't think the CLI spec lists all the commands we're planning to provide. What is missing?

E.g. something like `tessel wap --start` turns tessel into a wireless access point

(Moved here from https://github.com/tessel/v2-cli/pull/5)

**Comment by johnnyman727** [comment]
There are a few different scenarios that the spec currently doesn't cover like access points and ethernet configuration. The problem is that there are just so many different possible configurations. I submit that we should just expose
`tessel wap -n ssid -p password`: set the credentials and start up the access point
`tessel wap up`: start up the access point with previously provided credentials
`tessel wap down`: cancel the access point

For anything more complicated, people can ssh in directly and modify.
